/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProximosPassosRouteImport } from './routes/proximos-passos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as CotacaoRouteImport } from './routes/cotacao'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as IndexRouteImport } from './routes/index'

const ProximosPassosRoute = ProximosPassosRouteImport.update({
  id: '/proximos-passos',
  path: '/proximos-passos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoRoute = CotacaoRouteImport.update({
  id: '/cotacao',
  path: '/cotacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/cotacao': typeof CotacaoRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/proximos-passos': typeof ProximosPassosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/cotacao': typeof CotacaoRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/proximos-passos': typeof ProximosPassosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/cotacao': typeof CotacaoRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/proximos-passos': typeof ProximosPassosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/confirmacao'
    | '/cotacao'
    | '/dados'
    | '/historico'
    | '/proximos-passos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/confirmacao'
    | '/cotacao'
    | '/dados'
    | '/historico'
    | '/proximos-passos'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/confirmacao'
    | '/cotacao'
    | '/dados'
    | '/historico'
    | '/proximos-passos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  CotacaoRoute: typeof CotacaoRoute
  DadosRoute: typeof DadosRoute
  HistoricoRoute: typeof HistoricoRoute
  ProximosPassosRoute: typeof ProximosPassosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proximos-passos': {
      id: '/proximos-passos'
      path: '/proximos-passos'
      fullPath: '/proximos-passos'
      preLoaderRoute: typeof ProximosPassosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao': {
      id: '/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof CotacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  CotacaoRoute: CotacaoRoute,
  DadosRoute: DadosRoute,
  HistoricoRoute: HistoricoRoute,
  ProximosPassosRoute: ProximosPassosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
